apiVersion: v1
kind: Pod
metadata:
  name: pubnub-source-test
  namespace: kafka
spec:
  containers:
  - name: pubnub-source-test
    image: kawayu168/pubnub-kafka-source:latest
    env:
    - name: KAFKA_BROKER
      value: "broker"
    - name: KAFKA_TOPIC
      value: "test"
    - name: PUBNUB_SUBSCRIBE_KEY
      value: "sub-c-52a9ab50-291b-11e5-baaa-0619f8945a4f"
    - name: PUBNUB_CHANNELS
      value: "lightning_ticker_BTC_JPY:lightning_ticker_FX_BTC_JPY"
