apiVersion: v1
kind: Pod
metadata:
  name: bastion
  namespace: kafka
spec:
  containers:
  - name: bastion
    image: kawayu168/debian-ssh-kafka:stretch
    env:
    - name: SSH_KEY
      value: "insert your public key here"
